### ISSUE TITLE
Error in destroy_dyntracer(dyntracer) : object 'dyntracer' not found

### ISSUE THREAD

**Issue by aviralg** [PRL-PRG/promisedyntracer#6]
Here is the trace:
```
[3/9] Executing file: /home/aviral/projects/promise-dyntracing-experiment/2018-01-07-13-43-19/vignettes/knitr-knit_print.R
 [1]  1  2  3  4  5  6  7  8  9 10
                   mpg cyl disp  hp drat    wt  qsec vs am gear carb
Mazda RX4         21.0   6  160 110 3.90 2.620 16.46  0  1    4    4
Mazda RX4 Wag     21.0   6  160 110 3.90 2.875 17.02  0  1    4    4
Datsun 710        22.8   4  108  93 3.85 2.320 18.61  1  1    4    1
Hornet 4 Drive    21.4   6  258 110 3.08 3.215 19.44  1  0    3    1
Hornet Sportabout 18.7   8  360 175 3.15 3.440 17.02  0  0    3    2
Valiant           18.1   6  225 105 2.76 3.460 20.22  1  0    3    1
This is cool.This is cool. list()
 list()
 list()
Error in destroy_dyntracer(dyntracer) : object 'dyntracer' not found
Calls: execute.external.programs ... source -> withVisible -> eval -> eval -> destroy_dyntracer
```

**Comment by aviralg** [comment]
Here is the source of this bug -

```
dyntracer <- create_dyntracer('/path/to/db.sqlite',verbose=FALSE)
dyntrace(dyntracer, {
    ...
    ...
    ...
    rm(list = ls(all = TRUE))
})
destroy_dyntracer(dyntracer)
```
The call to `rm` will remove all objects from environment including the `dyntracer` object. 
This causes the `destroy_dyntracer` command to fail.

**Comment by aviralg** [comment]
This is an issue with the way the scripts are written. Such scripts are few (we have encountered only 2 so far). There seems to be no clean way to address this problem without changing the design of the tracer. 2 vignettes is not a big enough input to drive that change. Not using results from those 2 vignettes should not have a difference on our analysis in a statistically significant way. I will let this issue linger on for now.

**Comment by kondziu** [comment]
It looks like the rm(...) is a cleanup mechanism. Maybe we can we fix the vignettes?

**Comment by aviralg** [comment]
Not sure. **Fixing** it means tampering with code which the user wrote. If we do that, we are not tracing what the user exactly wrote (though its very very close to what the user wrote). Also, this means we have some ad-hoc, manual steps to do for some vignettes. Imagine if this vignette is updated in newer versions of this package, we will have to manually update them again. Since the number of vignettes is small, this does not seem like a useful thing to do. The only reliable thing to do here is to somehow tinker with the `dyntracer`.

**Comment by aviralg** [comment]
[Fixed](https://github.com/PRL-PRG/promise-dyntracing-experiment/commit/cf117d222d5c66e62119529306edfc5ad220eed2)
